### ISSUE TITLE
Adding a README.md 

### ISSUE THREAD

**Issue by aaqsr** [azuregitter/Lilac#1]
![image](https://user-images.githubusercontent.com/36773044/81696163-055c9d80-947d-11ea-9324-3fde78b1d7a4.png)

**Comment by azuregitter** [comment]
did i do it right ![aaq](https://user-images.githubusercontent.com/65207737/81779471-604acf00-9527-11ea-85a0-45d69bc4b9e8.png)

**Comment by aaqsr** [comment]
Yes, perfect
